image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  # Install dependencies for devcontainers CLI
  - apk add --update nodejs npm python3 make g++
  # Install the devcontainers CLI
  - npm install -g @devcontainers/cli

# Build and Push Dev Container
build-devcontainer:
  stage: build
  script:
    # Log in to GitLab Container Registry
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    # Build and push the dev container image
    - devcontainer build --workspace-folder . --push true --image-name ${CI_REGISTRY_IMAGE}:latest

test-dbt-pipeline:
  stage: test
  tags:
    - shared
  image: ${CI_REGISTRY_IMAGE}:latest
  script:
    - poetry run python data_generator/main.py --dbt-model-path ./dbt_mimesis_example/seeds/schema.yml --output-path ./dbt_mimesis_example/seeds --min-rows=100 --max-rows=1000
    - cd dbt_mimesis_example poetry run dbt seed && poetry run dbt run && poetry run dbt test
