image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - test

build-devcontainer:
  stage: build
  tags:
    - shared
  script:
    - apk add --update nodejs npm python3 make g++
    - npm install -g @devcontainers/cli
    - devcontainer build --workspace-folder . --push false

test-dbt-pipeline:
  stage: test
  tags:
    - shared
  script:
    - devcontainer exec --workspace-folder . poetry run python data_generator/main.py --dbt-model-path ./dbt_mimesis_example/seeds/schema.yml --output-path ./dbt_mimesis_example/seeds --min-rows=100 --max-rows=1000
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt seed
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt run
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt test
