image: python:3.10-slim  # Use a lightweight Python base image

stages:
  - test

before_script:
  # Set up Poetry environment
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate

test:
  stage: test
  tags:
    - shared
  script:
    # Generate some test data
    - poetry --version
    - poetry run python data_generator/main.py \
      --dbt-model-path "./dbt_mimesis_example/seeds/schema.yml" \
      --output-path "./dbt_mimesis_example/seeds" \
      --min-rows 100 \
      --max-rows 1000
    # Run dbt
    - cd dbt_mimesis_example
    - poetry run dbt seed
    - poetry run dbt run
    - poetry run dbt test
