image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - build
  - test

build-devcontainer:
  stage: build
  tags:
    - shared
  script:
    # Install Node.js and @devcontainers/cli for building the devcontainer
    - apk add --no-cache nodejs npm python3 make g++
    - npm install -g @devcontainers/cli
    # Build the devcontainer image using @devcontainers/cli
    - devcontainer build --workspace-folder . --push false

test-dbt-pipeline:
  stage: test
  tags:
    - shared
  script:
    - devcontainer exec --workspace-folder . poetry run python data_generator/main.py --dbt-model-path ./dbt_mimesis_example/seeds/schema.yml --output-path ./dbt_mimesis_example/seeds --min-rows=100 --max-rows=1000
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt seed
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt run
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt test
