image: gcr.io/kaniko-project/executor:latest

variables:
  # Specify the directory for Kaniko's Docker configuration
  DOCKER_CONFIG: "/kaniko/.docker/"

stages:
  - build
  - test

# Build and Push Dev Container with Kaniko
build-devcontainer:
  stage: build
  tags:
    - shared
  script:
    # Authenticate with GitLab Container Registry
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # Build and push the dev container image using Kaniko
    - /kaniko/executor --context . --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE:latest

# Test DBT Pipeline Using Pre-Built Dev Container
test-dbt-pipeline:
  stage: test
  tags:
    - shared
  image: $CI_REGISTRY_IMAGE:latest
  script:
    # Run the Python script inside the pre-built devcontainer image
    - poetry run python data_generator/main.py --dbt-model-path ./dbt_mimesis_example/seeds/schema.yml --output-path ./dbt_mimesis_example/seeds --min-rows=100 --max-rows=1000
    # Run dbt commands inside the devcontainer image
    - poetry run dbt seed --profiles-dir ./dbt_mimesis_example
    - poetry run dbt run --profiles-dir ./dbt_mimesis_example
    - poetry run dbt test --profiles-dir ./dbt_mimesis_example
