image: python:3.10-slim  # Use a lightweight Python base image

stages:
  - test

cache:
  key: "${CI_COMMIT_REF_SLUG}"  # Cache key based on branch/commit
  paths:
    - .venv/  # Cache the virtual environment
    - .poetry/  # Cache Poetry installation

before_script:
  # Set up Poetry environment
  - export POETRY_HOME="$CI_PROJECT_DIR/.poetry"
  - curl -sSL https://install.python-poetry.org | python3 -
  - export PATH="$POETRY_HOME/bin:$PATH"  # Add Poetry to PATH
  - poetry config virtualenvs.in-project true  # Create venv in project folder
  - poetry install  # Install dependencies

test:
  stage: test
  tags:
    - shared
  script:
    # Generate some test data
    - poetry --version
    - poetry run python data_generator/main.py \
      --dbt-model-path ./dbt_mimesis_example/seeds/schema.yml \
      --output-path ./dbt_mimesis_example/seeds \
      --min-rows=100 \
      --max-rows=1000
    # Run dbt
    - cd dbt_mimesis_example
    - poetry run dbt seed
    - poetry run dbt run
    - poetry run dbt test
