image: python:3.10-slim  # Use a lightweight Python base image

stages:
  - test

cache:
  key: "${CI_COMMIT_REF_SLUG}"  # Cache key based on branch/commit
  paths:
    - .venv/  # Cache the virtual environment
    - .poetry/  # Cache Poetry installation

before_script:
  # Set up Poetry environment
  - export POETRY_HOME=.poetry
  - python3 -m venv $POETRY_HOME
  - $POETRY_HOME/bin/pip install poetry
  - $POETRY_HOME/bin/poetry config virtualenvs.in-project true
  - $POETRY_HOME/bin/poetry install

test:
  stage: test
  tags:
    - shared
  script:
    # Generate some test data
    - poetry run python data_generator/main.py \
      --dbt-model-path ./dbt_mimesis_example/seeds/schema.yml \
      --output-path ./dbt_mimesis_example/seeds \
      --min-rows=100 \
      --max-rows=1000
    # Run dbt
    - cd dbt_mimesis_example
    - poetry run dbt seed
    - poetry run dbt run
    - poetry run dbt test
