services:
  - docker:24.0.5-dind

stages:
  - build
  - test

build-devcontainer:
  stage: build
  tags:
    - shared
  script:
    # Install Docker
    - apk add --no-cache docker
    # Start the Docker daemon in the background
    - dockerd-entrypoint.sh & sleep 5
    # Verify Docker is installed and running
    - docker info
    # Install Node.js and @devcontainers/cli for building the devcontainer
    - apk add --no-cache nodejs npm python3 make g++
    - npm install -g @devcontainers/cli
    # Build the devcontainer image using @devcontainers/cli
    - devcontainer build --workspace-folder . --push false

test-dbt-pipeline:
  stage: test
  tags:
    - shared
  script:
    - devcontainer exec --workspace-folder . poetry run python data_generator/main.py --dbt-model-path ./dbt_mimesis_example/seeds/schema.yml --output-path ./dbt_mimesis_example/seeds --min-rows=100 --max-rows=1000
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt seed
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt run
    - devcontainer exec --workspace-folder ./dbt_mimesis_example poetry run dbt test
