image: python:3.10-slim  # Use a lightweight Python base image

stages:
  - test

before_script:
  # Set up environment
  - apt-get update && apt-get install -y git
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate
  # Install dependencies including wget
  - apt-get update && apt-get install -y wget unzip git
  # Install DuckDB CLI
  - wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip
  - unzip duckdb_cli-linux-amd64.zip -d /usr/local/bin/
  - chmod +x /usr/local/bin/duckdb
  # Verify installation
  - duckdb --version
  - mkdir -p /workspaces/dbt-mimesis/dbt_mimesis_example/
  - duckdb /workspaces/dbt-mimesis/dbt_mimesis_example/dev.duckdb "SELECT 'Database created successfully';"

test:
  stage: test
  tags:
    - shared
  only:
    - merge_requests
    - main
  script:
    # Generate some test data
    - python data_generator/main.py --dbt-model-path "./dbt_mimesis_example/seeds/schema.yml" --output-path "./dbt_mimesis_example/seeds" --min-rows 100 --max-rows 1000
    # Run dbt
    - cd dbt_mimesis_example
    - dbt deps
    - dbt seed
    - dbt run
    - dbt test
