version: 2
models:
  - name: flights
    config:
      contract: {enforced: true}
    columns:
      - name: FlightDate
        description: Start date of flight
        data_type: date
        quote: true
        data_tests:
          - not_null
      - name: CarrierName
        description: Airline hosting the flight
        data_type: varchar
        quote: true
        data_tests:
          - not_null
      - name: AirplaneModelId
        description: ID of the airplane model
        data_type: integer
        quote: true
        constraints:
          - type: not_null
          - type: foreign_key
            expression: "airplanes (Id)"
        data_tests:
          - not_null
      - name: OriginCityId
        description: ID of the City where the airplane took of
        data_type: integer
        quote: true
        constraints:
          - type: not_null
          - type: foreign_key
            expression: "cities (Id)"
      - name: DestCityId
        description: ID of the City where the plane landet
        data_type: integer
        quote: true
        constraints:
          - type: not_null
          - type: foreign_key
            expression: "cities (Id)"
  - name: cities
    config:
      contract: {enforced: true}
    columns:
      - name: Id
        description: Unique identifier for a city
        data_type: integer
        quote: true
        constraints:
          - type: not_null
          - type: unique
          - type: primary_key
      - name: CityName
        description: Name of the city
        data_type: varchar
        quote: true
        data_tests:
          - not_null
          - unique

  - name: airplanes
    config:
      contract: {enforced: true}
    columns:
      - name: Id
        description: Unique Identifier for an airplane
        data_type: integer
        quote: true
        constraints:
          - type: not_null
          - type: unique
          - type: primary_key
      - name: AirplaneModel
        description: Name of the Airplane model
        data_type: varchar
        quote: true
        data_tests:
          - not_null
          - unique
      - name: NumSeats
        description: Number of seats the Airplane has
        data_type: integer
        quote: true
        data_tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
