version: 2
models:
  - name: origin_city
    columns:
      - name: OriginCityName
        description: City where the airplane took of
        data_type: varchar
        quote: true
        data_tests:
          - not_null
          - unique
