version: 2
seeds:
  - name: raw_airplanes
    columns:
      - name: AirplaneModel
        description: Name of the Airplane model
        data_type: varchar
        quote: true
        data_tests:
          - not_null
          - unique
        meta:
          primary_key: true
      - name: NumSeats
        description: Number of seats the Airplane has
        data_type: integer
        quote: true

  - name: raw_flights
    columns:
      - name: FlightDate
        description: Start date of flight
        data_type: date
        quote: true
        data_tests:
          - not_null
      - name: CarrierName
        description: Name of the airline hosting the flight
        data_type: varchar
        quote: true
        data_tests:
          - not_null
      - name: AirplaneModel
        description: Name of the airplane model
        data_type: varchar
        quote: true
        data_tests:
          - not_null
        meta:
          foreign_key: raw_airplanes.AirplaneModel
      - name: OriginCityName
        description: City where the airplane took of
        data_type: varchar
        data_tests:
          - not_null
        quote: true
      - name: DestCityName
        description: City where the plane landed
        data_type: varchar
        quote: true
        data_tests:
          - not_null
